### ISSUE TITLE
Function clause doesn't match for Ecto.DateTime.to_erl/1

### ISSUE THREAD

**Issue by axelclark** [axelclark/ex338#252]
Integration with Elixir 1.3 calendar types

Ecto now supports the following native types :date, :time, :naive_datetime and :utc_datetime that map to Elixir types Date, Time, NaiveDateTime and DateTime respectively. :naive_datetime has no timezone information, while :utc_datetime expects the data is stored in the database in the "Etc/UTC" timezone.

Ecto 2.1 also changed the defaults in Ecto.Schema.timestamps/0 to use :naive_datetime as type instead of Ecto.DateTime and to include microseconds by default. You can revert to the previous defaults by setting the following before your schema/2 call:

@timestamps_opts [type: Ecto.DateTime, usec: false]
The old Ecto types (Ecto.Date, Ecto.Time and Ecto.DateTime) are now deprecated.

**Comment by axelclark** [comment]
```
  2) test index/2 lists all trades in a league (Ex338.TradeControllerTest)
     test/controllers/trade_controller_test.exs:10
     ** (FunctionClauseError) no function clause matching in Ex338.ViewHelpers.pretty_date/1
     stacktrace:
       (ex338) web/views/view_helpers.ex:19: Ex338.ViewHelpers.pretty_date(~N[2017-03-06 00:25:49.238848])
       (ex338) web/templates/trade/index.html.eex:18: anonymous fn/2 in Ex338.TradeView.index.html/1
       (elixir) lib/enum.ex:1755: Enum."-reduce/3-lists^foldl/2-0-"/3
       (ex338) web/templates/trade/index.html.eex:15: Ex338.TradeView."index.html"/1
       (ex338) web/templates/layout/app.html.eex:15: Ex338.LayoutView."app.html"/1
       (phoenix) lib/phoenix/view.ex:335: Phoenix.View.render_to_iodata/3
       (phoenix) lib/phoenix/controller.ex:642: Phoenix.Controller.do_render/4
       (ex338) web/controllers/trade_controller.ex:1: Ex338.TradeController.action/2
       (ex338) web/controllers/trade_controller.ex:1: Ex338.TradeController.phoenix_controller_pipeline/2
       (ex338) lib/ex338/endpoint.ex:1: Ex338.Endpoint.instrument/4
       (ex338) lib/phoenix/router.ex:261: Ex338.Router.dispatch/2
       (ex338) web/router.ex:1: Ex338.Router.do_call/2
       (ex338) web/router.ex:5: Ex338.Router."call (overridable 2)"/2
       (ex338) lib/plug/error_handler.ex:64: Ex338.Router.call/2
       (ex338) lib/ex338/endpoint.ex:1: Ex338.Endpoint.phoenix_pipeline/1
       (ex338) lib/ex338/endpoint.ex:1: Ex338.Endpoint.call/2
       (phoenix) lib/phoenix/test/conn_test.ex:224: Phoenix.ConnTest.dispatch/5
       test/controllers/trade_controller_test.exs:24: (test)



  3) test index/2 lists all injured reserve transactions in a league (Ex338.InjuredReserveControllerTest)
     test/controllers/injured_reserve_controller_test.exs:11
     ** (FunctionClauseError) no function clause matching in Ecto.DateTime.to_erl/1
     stacktrace:
       (ecto) lib/ecto/date_time.ex:608: Ecto.DateTime.to_erl(~N[2017-03-06 00:25:49.289799])
       (ex338) web/views/view_helpers.ex:31: Ex338.ViewHelpers.short_datetime_pst/1
       (ex338) web/templates/injured_reserve/table.html.eex:15: anonymous fn/2 in Ex338.InjuredReserveView.table.html/1
       (elixir) lib/enum.ex:1755: Enum."-reduce/3-lists^foldl/2-0-"/3
       (ex338) web/templates/injured_reserve/table.html.eex:13: Ex338.InjuredReserveView."table.html"/1
       (ex338) web/templates/injured_reserve/index.html.eex:8: Ex338.InjuredReserveView."index.html"/1
       (ex338) web/templates/layout/app.html.eex:15: Ex338.LayoutView."app.html"/1
       (phoenix) lib/phoenix/view.ex:335: Phoenix.View.render_to_iodata/3
       (phoenix) lib/phoenix/controller.ex:642: Phoenix.Controller.do_render/4
       (ex338) web/controllers/injured_reserve_controller.ex:1: Ex338.InjuredReserveController.action/2
       (ex338) web/controllers/injured_reserve_controller.ex:1: Ex338.InjuredReserveController.phoenix_controller_pipeline/2
       (ex338) lib/ex338/endpoint.ex:1: Ex338.Endpoint.instrument/4
       (ex338) lib/phoenix/router.ex:261: Ex338.Router.dispatch/2
       (ex338) web/router.ex:1: Ex338.Router.do_call/2
       (ex338) web/router.ex:5: Ex338.Router."call (overridable 2)"/2
       (ex338) lib/plug/error_handler.ex:64: Ex338.Router.call/2
       (ex338) lib/ex338/endpoint.ex:1: Ex338.Endpoint.phoenix_pipeline/1
       (ex338) lib/ex338/endpoint.ex:1: Ex338.Endpoint.call/2
       (phoenix) lib/phoenix/test/conn_test.ex:224: Phoenix.ConnTest.dispatch/5
       test/controllers/injured_reserve_controller_test.exs:25: (test)
```
