### ISSUE TITLE
Need to get a consistent plan with dates

### ISSUE THREAD

**Issue by axelclark** [axelclark/ex338#256]
Ecto.DateTime is being deprecated and timestamps is using NaiveDateTime.

**Comment by axelclark** [comment]
```elixir
warning: Ecto.DateTime is deprecated, plese use :naive_datetime instead
  lib/ecto/schema.ex:1872: Ecto.Schema.check_type!/3
  lib/ecto/schema.ex:1507: Ecto.Schema.__field__/4
  lib/ex338/waiver.ex:19: (module)
  (elixir) src/elixir_compiler.erl:85: :elixir_compiler.dispatch/6
  (elixir) src/elixir_module.erl:238: :elixir_module.eval_form/6
  (elixir) src/elixir_module.erl:80: :elixir_module.compile/5
  (stdlib) erl_eval.erl:670: :erl_eval.do_apply/6
  (elixir) src/elixir.erl:239: :elixir.eval_forms/4
  (elixir) src/elixir_compiler.erl:61: :elixir_compiler.eval_forms/3
  (elixir) src/elixir_lexical.erl:17: :elixir_lexical.run/3
  (elixir) src/elixir_compiler.erl:27: :elixir_compiler.quoted/3
  (elixir) lib/kernel/parallel_compiler.ex:121: anonymous fn/4 in Kernel.ParallelCompiler.spawn_compilers/1

warning: Ecto.DateTime is deprecated, plese use :naive_datetime instead
  lib/ecto/schema.ex:1872: Ecto.Schema.check_type!/3
  lib/ecto/schema.ex:1507: Ecto.Schema.__field__/4
  lib/ex338/coherence/user.ex:15: (module)
  (elixir) src/elixir_compiler.erl:85: :elixir_compiler.dispatch/6
  (elixir) src/elixir_module.erl:238: :elixir_module.eval_form/6
  (elixir) src/elixir_module.erl:80: :elixir_module.compile/5
  (stdlib) erl_eval.erl:670: :erl_eval.do_apply/6
  (elixir) src/elixir.erl:239: :elixir.eval_forms/4
  (elixir) src/elixir_compiler.erl:61: :elixir_compiler.eval_forms/3
  (elixir) src/elixir_lexical.erl:17: :elixir_lexical.run/3
  (elixir) src/elixir_compiler.erl:27: :elixir_compiler.quoted/3
  (elixir) lib/kernel/parallel_compiler.ex:121: anonymous fn/4 in Kernel.ParallelCompiler.spawn_compilers/1

warning: Ecto.DateTime is deprecated, plese use :naive_datetime instead
  lib/ecto/schema.ex:1872: Ecto.Schema.check_type!/3
  lib/ecto/schema.ex:1507: Ecto.Schema.__field__/4
  lib/ex338/coherence/user.ex:15: (module)
  (elixir) src/elixir_compiler.erl:85: :elixir_compiler.dispatch/6
  (elixir) src/elixir_module.erl:238: :elixir_module.eval_form/6
  (elixir) src/elixir_module.erl:80: :elixir_module.compile/5
  (stdlib) erl_eval.erl:670: :erl_eval.do_apply/6
  (elixir) src/elixir.erl:239: :elixir.eval_forms/4
  (elixir) src/elixir_compiler.erl:61: :elixir_compiler.eval_forms/3
  (elixir) src/elixir_lexical.erl:17: :elixir_lexical.run/3
  (elixir) src/elixir_compiler.erl:27: :elixir_compiler.quoted/3
  (elixir) lib/kernel/parallel_compiler.ex:121: anonymous fn/4 in Kernel.ParallelCompiler.spawn_compilers/1

warning: Ecto.DateTime is deprecated, plese use :naive_datetime instead
  lib/ecto/schema.ex:1872: Ecto.Schema.check_type!/3
  lib/ecto/schema.ex:1507: Ecto.Schema.__field__/4
  lib/ex338/coherence/user.ex:15: (module)
  (elixir) src/elixir_compiler.erl:85: :elixir_compiler.dispatch/6
  (elixir) src/elixir_module.erl:238: :elixir_module.eval_form/6
  (elixir) src/elixir_module.erl:80: :elixir_module.compile/5
  (stdlib) erl_eval.erl:670: :erl_eval.do_apply/6
  (elixir) src/elixir.erl:239: :elixir.eval_forms/4
  (elixir) src/elixir_compiler.erl:61: :elixir_compiler.eval_forms/3
  (elixir) src/elixir_lexical.erl:17: :elixir_lexical.run/3
  (elixir) src/elixir_compiler.erl:27: :elixir_compiler.quoted/3
  (elixir) lib/kernel/parallel_compiler.ex:121: anonymous fn/4 in Kernel.ParallelCompiler.spawn_compilers/1

warning: Ecto.DateTime is deprecated, plese use :naive_datetime instead
  lib/ecto/schema.ex:1872: Ecto.Schema.check_type!/3
  lib/ecto/schema.ex:1507: Ecto.Schema.__field__/4
  lib/ex338/coherence/user.ex:15: (module)
  (elixir) src/elixir_compiler.erl:85: :elixir_compiler.dispatch/6
  (elixir) src/elixir_module.erl:238: :elixir_module.eval_form/6
  (elixir) src/elixir_module.erl:80: :elixir_module.compile/5
  (stdlib) erl_eval.erl:670: :erl_eval.do_apply/6
  (elixir) src/elixir.erl:239: :elixir.eval_forms/4
  (elixir) src/elixir_compiler.erl:61: :elixir_compiler.eval_forms/3
  (elixir) src/elixir_lexical.erl:17: :elixir_lexical.run/3
  (elixir) src/elixir_compiler.erl:27: :elixir_compiler.quoted/3
  (elixir) lib/kernel/parallel_compiler.ex:121: anonymous fn/4 in Kernel.ParallelCompiler.spawn_compilers/1

warning: Ecto.DateTime is deprecated, plese use :naive_datetime instead
  lib/ecto/schema.ex:1872: Ecto.Schema.check_type!/3
  lib/ecto/schema.ex:1507: Ecto.Schema.__field__/4
  lib/ex338/coherence/user.ex:15: (module)
  (elixir) src/elixir_compiler.erl:85: :elixir_compiler.dispatch/6
  (elixir) src/elixir_module.erl:238: :elixir_module.eval_form/6
  (elixir) src/elixir_module.erl:80: :elixir_module.compile/5
  (stdlib) erl_eval.erl:670: :erl_eval.do_apply/6
  (elixir) src/elixir.erl:239: :elixir.eval_forms/4
  (elixir) src/elixir_compiler.erl:61: :elixir_compiler.eval_forms/3
  (elixir) src/elixir_lexical.erl:17: :elixir_lexical.run/3
  (elixir) src/elixir_compiler.erl:27: :elixir_compiler.quoted/3
  (elixir) lib/kernel/parallel_compiler.ex:121: anonymous fn/4 in Kernel.ParallelCompiler.spawn_compilers/1

warning: Ecto.DateTime is deprecated, plese use :naive_datetime instead
  lib/ecto/schema.ex:1872: Ecto.Schema.check_type!/3
  lib/ecto/schema.ex:1507: Ecto.Schema.__field__/4
  lib/ex338/championship.ex:13: (module)
  (elixir) src/elixir_compiler.erl:85: :elixir_compiler.dispatch/6
  (elixir) src/elixir_module.erl:238: :elixir_module.eval_form/6
  (elixir) src/elixir_module.erl:80: :elixir_module.compile/5
  (stdlib) erl_eval.erl:670: :erl_eval.do_apply/6
  (elixir) src/elixir.erl:239: :elixir.eval_forms/4
  (elixir) src/elixir_compiler.erl:61: :elixir_compiler.eval_forms/3
  (elixir) src/elixir_lexical.erl:17: :elixir_lexical.run/3
  (elixir) src/elixir_compiler.erl:27: :elixir_compiler.quoted/3
  (elixir) lib/kernel/parallel_compiler.ex:121: anonymous fn/4 in Kernel.ParallelCompiler.spawn_compilers/1

warning: Ecto.DateTime is deprecated, plese use :naive_datetime instead
  lib/ecto/schema.ex:1872: Ecto.Schema.check_type!/3
  lib/ecto/schema.ex:1507: Ecto.Schema.__field__/4
  lib/ex338/championship.ex:14: (module)
  (elixir) src/elixir_compiler.erl:85: :elixir_compiler.dispatch/6
  (elixir) src/elixir_module.erl:238: :elixir_module.eval_form/6
  (elixir) src/elixir_module.erl:80: :elixir_module.compile/5
  (stdlib) erl_eval.erl:670: :erl_eval.do_apply/6
  (elixir) src/elixir.erl:239: :elixir.eval_forms/4
  (elixir) src/elixir_compiler.erl:61: :elixir_compiler.eval_forms/3
  (elixir) src/elixir_lexical.erl:17: :elixir_lexical.run/3
  (elixir) src/elixir_compiler.erl:27: :elixir_compiler.quoted/3
  (elixir) lib/kernel/parallel_compiler.ex:121: anonymous fn/4 in Kernel.ParallelCompiler.spawn_compilers/1

warning: Ecto.DateTime is deprecated, plese use :naive_datetime instead
  lib/ecto/schema.ex:1872: Ecto.Schema.check_type!/3
  lib/ecto/schema.ex:1507: Ecto.Schema.__field__/4
  lib/ex338/championship.ex:15: (module)
  (elixir) src/elixir_compiler.erl:85: :elixir_compiler.dispatch/6
  (elixir) src/elixir_module.erl:238: :elixir_module.eval_form/6
  (elixir) src/elixir_module.erl:80: :elixir_module.compile/5
  (stdlib) erl_eval.erl:670: :erl_eval.do_apply/6
  (elixir) src/elixir.erl:239: :elixir.eval_forms/4
  (elixir) src/elixir_compiler.erl:61: :elixir_compiler.eval_forms/3
  (elixir) src/elixir_lexical.erl:17: :elixir_lexical.run/3
  (elixir) src/elixir_compiler.erl:27: :elixir_compiler.quoted/3
  (elixir) lib/kernel/parallel_compiler.ex:121: anonymous fn/4 in Kernel.ParallelCompiler.spawn_compilers/1

warning: Ecto.DateTime is deprecated, plese use :naive_datetime instead
  lib/ecto/schema.ex:1872: Ecto.Schema.check_type!/3
  lib/ecto/schema.ex:1507: Ecto.Schema.__field__/4
  lib/ex338/roster_position.ex:22: (module)
  (elixir) src/elixir_compiler.erl:85: :elixir_compiler.dispatch/6
  (elixir) src/elixir_module.erl:238: :elixir_module.eval_form/6
  (elixir) src/elixir_module.erl:80: :elixir_module.compile/5
  (stdlib) erl_eval.erl:670: :erl_eval.do_apply/6
  (elixir) src/elixir.erl:239: :elixir.eval_forms/4
  (elixir) src/elixir_compiler.erl:61: :elixir_compiler.eval_forms/3
  (elixir) src/elixir_lexical.erl:17: :elixir_lexical.run/3
  (elixir) src/elixir_compiler.erl:27: :elixir_compiler.quoted/3
  (elixir) lib/kernel/parallel_compiler.ex:121: anonymous fn/4 in Kernel.ParallelCompiler.spawn_compilers/1

warning: Ecto.DateTime is deprecated, plese use :naive_datetime instead
  lib/ecto/schema.ex:1872: Ecto.Schema.check_type!/3
  lib/ecto/schema.ex:1507: Ecto.Schema.__field__/4
  lib/ex338/roster_position.ex:23: (module)
  (elixir) src/elixir_compiler.erl:85: :elixir_compiler.dispatch/6
  (elixir) src/elixir_module.erl:238: :elixir_module.eval_form/6
  (elixir) src/elixir_module.erl:80: :elixir_module.compile/5
  (stdlib) erl_eval.erl:670: :erl_eval.do_apply/6
  (elixir) src/elixir.erl:239: :elixir.eval_forms/4
  (elixir) src/elixir_compiler.erl:61: :elixir_compiler.eval_forms/3
  (elixir) src/elixir_lexical.erl:17: :elixir_lexical.run/3
  (elixir) src/elixir_compiler.erl:27: :elixir_compiler.quoted/3
  (elixir) lib/kernel/parallel_compiler.ex:121: anonymous fn/4 in Kernel.ParallelCompiler.spawn_compilers/1
```
