### ISSUE TITLE
Bug in Waiver Test

### ISSUE THREAD

**Issue by axelclark** [axelclark/ex338#346]
Bug identified in waiver test when running travis:
```elixir
1) test create/2 creates a waiver and redirects (Ex338Web.WaiverControllerTest)
 test/ex338_web/controllers/waiver_controller_test.exs:65
 ** (Ecto.ConstraintError) constraint error when attempting to insert struct:
 * unique: users_pkey
 If you would like to convert this constraint into an error, please
 call unique_constraint/3 in your changeset and define the proper
 constraint name. The changeset has not defined any constraint.
 code: insert(:owner, fantasy_team: team, user: conn.assigns.current_user)
 stacktrace:
 (ecto) lib/ecto/repo/schema.ex:495: anonymous fn/4 in Ecto.Repo.Schema.constraints_to_errors/3
 (elixir) lib/enum.ex:1270: Enum."-map/2-lists^map/1-0-"/2
 (ecto) lib/ecto/repo/schema.ex:481: Ecto.Repo.Schema.constraints_to_errors/3
 (ecto) lib/ecto/repo/schema.ex:213: anonymous fn/13 in Ecto.Repo.Schema.do_insert/4
 (ecto) lib/ecto/association.ex:762: Ecto.Association.BelongsTo.on_repo_change/4
 (ecto) lib/ecto/association.ex:313: Ecto.Association.on_repo_change/6
 (elixir) lib/enum.ex:1826: Enum."-reduce/3-lists^foldl/2-0-"/3
 (ecto) lib/ecto/association.ex:293: Ecto.Association.on_repo_change/3
 (ecto) lib/ecto/repo/schema.ex:598: Ecto.Repo.Schema.process_parents/3
 (ecto) lib/ecto/repo/schema.ex:193: anonymous fn/13 in Ecto.Repo.Schema.do_insert/4
 (ecto) lib/ecto/repo/schema.ex:691: anonymous fn/3 in Ecto.Repo.Schema.wrap_in_transaction/6
 (ecto) lib/ecto/adapters/sql.ex:620: anonymous fn/3 in Ecto.Adapters.SQL.do_transaction/3
 (db_connection) lib/db_connection.ex:1275: DBConnection.transaction_run/4
 (db_connection) lib/db_connection.ex:1199: DBConnection.run_begin/3
 (db_connection) lib/db_connection.ex:790: DBConnection.transaction/3
 (ecto) lib/ecto/repo/schema.ex:131: Ecto.Repo.Schema.insert!/4
 test/ex338_web/controllers/waiver_controller_test.exs:68: (test)
.....[%Ex338.User{__meta__: #Ecto.Schema.Metadata<:loaded, "users">, admin: false,
 current_password: nil, current_sign_in_at: nil, current_sign_in_ip: nil,
 email: "user8D833D011171D894@example.com", failed_attempts: 0,
 fantasy_teams: #Ecto.Association.NotLoaded<association :fantasy_teams is not loaded>,
 id: 4, inserted_at: ~N[2017-10-23 00:27:02.564382], last_sign_in_at: nil,
 last_sign_in_ip: nil, locked_at: nil, name: "Some User",
 owners: #Ecto.Association.NotLoaded<association :owners is not loaded>,
 password: nil, password_confirmation: nil,
 password_hash: "$2b$04$rujYFliPPZTU5jTGymPvG.jBeMHZ5lRy9aWw7l28BMlSDMy7k.bmy",
 remember_created_at: nil, reset_password_sent_at: nil,
 reset_password_token: nil, sign_in_count: 0, unlock_token: nil,
 updated_at: ~N[2017-10-23 00:27:02.564391]},
 %Ex338.User{__meta__: #Ecto.Schema.Metadata<:loaded, "users">, admin: false,
 current_password: nil, current_sign_in_at: nil, current_sign_in_ip: nil,
 email: "test@example.com", failed_attempts: 0,
 fantasy_teams: #Ecto.Association.NotLoaded<association :fantasy_teams is not loaded>,
 id: 1, inserted_at: ~N[2017-10-23 00:27:02.565622], last_sign_in_at: nil,
 last_sign_in_ip: nil, locked_at: nil, name: "test",
 owners: #Ecto.Association.NotLoaded<association :owners is not loaded>,
 password: nil, password_confirmation: nil, password_hash: nil,
 remember_created_at: nil, reset_password_sent_at: nil,
 reset_password_token: nil, sign_in_count: 0, unlock_token: nil,
 updated_at: ~N[2017-10-23 00:27:02.565630]}]
[%Ex338.Owner{__meta__: #Ecto.Schema.Metadata<:loaded, "owners">,
 fantasy_team: #Ecto.Association.NotLoaded<association :fantasy_team is not loaded>,
 fantasy_team_id: 39, id: 3, inserted_at: ~N[2017-10-23 00:27:02.566085],
 updated_at: ~N[2017-10-23 00:27:02.566092],
 user: #Ecto.Association.NotLoaded<association :user is not loaded>,
 user_id: 1}]
..[%Ex338.User{__meta__: #Ecto.Schema.Metadata<:loaded, "users">, admin: false,
 current_password: nil, current_sign_in_at: nil, current_sign_in_ip: nil,
 email: "user3C897BF0E540E433@example.com", failed_attempts: 0,
 fantasy_teams: #Ecto.Association.NotLoaded<association :fantasy_teams is not loaded>,
 id: 5, inserted_at: ~N[2017-10-23 00:27:02.613223], last_sign_in_at: nil,
 last_sign_in_ip: nil, locked_at: nil, name: "Some User",
 owners: #Ecto.Association.NotLoaded<association :owners is not loaded>,
 password: nil, password_confirmation: nil,
 password_hash: "$2b$04$rebiSamXNTnvuO5gRSvzFe2ZaQdoXVuaVT/MqwY47ujWKg8gsCBGO",
 remember_created_at: nil, reset_password_sent_at: nil,
 reset_password_token: nil, sign_in_count: 0, unlock_token: nil,
 updated_at: ~N[2017-10-23 00:27:02.613231]},
 %Ex338.User{__meta__: #Ecto.Schema.Metadata<:loaded, "users">, admin: false,
 current_password: nil, current_sign_in_at: nil, current_sign_in_ip: nil,
 email: "test@example.com", failed_attempts: 0,
 fantasy_teams: #Ecto.Association.NotLoaded<association :fantasy_teams is not loaded>,
 id: 1, inserted_at: ~N[2017-10-23 00:27:02.614254], last_sign_in_at: nil,
 last_sign_in_ip: nil, locked_at: nil, name: "test",
 owners: #Ecto.Association.NotLoaded<association :owners is not loaded>,
 password: nil, password_confirmation: nil, password_hash: nil,
 remember_created_at: nil, reset_password_sent_at: nil,
 reset_password_token: nil, sign_in_count: 0, unlock_token: nil,
 updated_at: ~N[2017-10-23 00:27:02.614260]}]
[%Ex338.Owner{__meta__: #Ecto.Schema.Metadata<:loaded, "owners">,
 fantasy_team: #Ecto.Association.NotLoaded<association :fantasy_team is not loaded>,
 fantasy_team_id: 41, id: 4, inserted_at: ~N[2017-10-23 00:27:02.614629],
 updated_at: ~N[2017-10-23 00:27:02.614634],
 user: #Ecto.Association.NotLoaded<association :user is not loaded>,
 user_id: 1}]
```

**Comment by axelclark** [comment]
Two users were created due to error in factory setup.

**Comment by axelclark** [comment]
Closed with https://github.com/axelclark/ex338/pull/342/commits/4f3ed82e39a4a75b62760e8007d63b0e394960f0
