### ISSUE TITLE
Remove wallaby

### ISSUE THREAD

**Issue by axelclark** [axelclark/ex338#517]
```
** (MatchError) no match of right hand side value: {:error, {:wallaby, {:bad_return, {{Wallaby, :start, [:normal, []]}, {:EXIT, {%Wallaby.DependencyError{message: "Wallaby can't find phantomjs. Make sure you have phantomjs installed\nand included in your path, or that your `config :wallaby, :phantomjs`\nsetting points to a valid phantomjs executable.\n"}, [{Wallaby, :start, 2, [file: 'lib/wallaby.ex', line: 29]}, {:application_master, :start_it_old, 4, [file: 'application_master.erl', line: 277]}]}}}}}}
    test/test_helper.exs:1: (file)
    (elixir) lib/code.ex:767: Code.require_file/2
    (elixir) lib/enum.ex:765: Enum."-each/2-lists^foreach/1-0-"/2
    (elixir) lib/enum.ex:765: Enum.each/2
```

**Comment by axelclark** [comment]
Reverts 6e43ef1
